export const SITE_URL = "https://swift-share-tau.vercel.app";
export const MAX_UPLOAD_BYTES = 250 * 1024 * 1024;

export const formatFileSize = (bytes: number) => {
  if (bytes === 0) return "0 B";

  const units = ["B", "KB", "MB", "GB"];
  const unitIndex = Math.min(
    Math.floor(Math.log(bytes) / Math.log(1024)),
    units.length - 1,
  );

  const value = bytes / 1024 ** unitIndex;
  const formatted = unitIndex === 0 || Number.isInteger(value)
    ? value.toFixed(0)
    : value.toFixed(1);

  return `${formatted} ${units[unitIndex]}`;
};

export const FILE_SHARING_KEYWORDS = [
  "file sharing",
  "share files online",
  "send files",
  "upload files online",
  "file transfer",
  "free file sharing",
  "share files with link",
  "transfer files for free",
  "share files without signup",
  "online file sharing",
  "share documents online",
  "share photos and videos",
  "temporary file sharing",
  "expiring file links",
  "secure file sharing",
  "download files online",
  "file sharing website",
  "send large files",
];

export const useCases = [
  {
    path: "/share-files",
    title: "Share files online",
    shortTitle: "Files",
    description:
      "Send a file with a link. No account to create, no shared folder to manage, and up to 250 MB per file.",
    h1: "Share files online",
    detailTitle: "A file to send. A link to share.",
    detail: "Send a project handoff, a document, or a file for another device. Each upload gets its own download link, QR code, and six-character file code.",
    tipTitle: "Sending more than one file?",
    tip: "Put your files in a ZIP archive before uploading to share them together. Keep a copy of the originals: SwiftShare links are temporary.",
    keywords: [
      "share files online",
      "send files",
      "upload and share files",
      ...FILE_SHARING_KEYWORDS,
      "share files",
      "file share",
      "online file sharing",
      "share files with link",
    ],
  },
  {
    path: "/share-text",
    title: "Share copied text",
    shortTitle: "Text",
    description:
      "Turn notes, code snippets, or copied text into a file you can share with a link.",
    h1: "Paste text and share it as a file",
    detailTitle: "Give your text a file of its own",
    detail: "Share meeting notes, a command, or a log without squeezing it into a chat message. Your recipient downloads the text as a file, ready to open in their preferred editor.",
    tipTitle: "Name it for the person receiving it",
    tip: "Use a name such as meeting-notes.txt or debug-log.txt so the file is easy to recognize later. Check logs and snippets for passwords or personal information before sharing.",
    keywords: [
      "share text online",
      "paste and share text",
      "share notes",
      "share code snippets",
      "share logs online",
      "share copied text",
      "text sharing tool",
      "pastebin alternative",
      "share text with link",
      "send text files",
      ...FILE_SHARING_KEYWORDS,
    ],
  },
  {
    path: "/share-apk",
    title: "Share APK files",
    shortTitle: "APK",
    description:
      "Get your Android build to testers and teammates with a temporary download link or QR code.",
    h1: "Share APK files with testers",
    detailTitle: "Send the build your team needs",
    detail: "Share an APK for a test session or a quick review. Testers can download the file on their Android device without creating a SwiftShare account.",
    tipTitle: "Make each build easy to identify",
    tip: "Include the app name and version in the filename. Downloading an APK does not install it; recipients manage installation and device permissions separately.",
    keywords: [
      "share apk",
      "send apk file",
      "apk upload",
      "share apk with link",
      "upload apk online",
      "send apk to testers",
      "apk download link",
      "share android apps",
      "apk file transfer",
      "share apk file online",
      "android apk sharing",
      "apk share link",
      ...FILE_SHARING_KEYWORDS,
    ],
  },
  {
    path: "/share-json",
    title: "Share JSON files",
    shortTitle: "JSON",
    description:
      "Share a JSON file or paste an API response, sample dataset, or configuration for a teammate to download.",
    h1: "Share JSON files",
    detailTitle: "Keep the context with the data",
    detail: "Pass along a sample response for debugging or a dataset for review. Upload an existing JSON file, or paste the text and give it a filename ending in .json.",
    tipTitle: "Check the content before sharing",
    tip: "SwiftShare shares your text as provided; it does not validate or format JSON. Remove API keys, tokens, and personal data from your sample first.",
    keywords: [
      "share json",
      "json file sharing",
      "paste json",
      "share json online",
      "send json files",
      "upload json file",
      "share json with developers",
      "json debugging",
      "api test json sharing",
      "share json data",
      "json paste tool",
      ...FILE_SHARING_KEYWORDS,
    ],
  },
  {
    path: "/large-file-transfer",
    title: `Send files up to ${formatFileSize(MAX_UPLOAD_BYTES)}`,
    shortTitle: "Large Files",
    description:
      `Send a video, archive, or project file up to ${formatFileSize(MAX_UPLOAD_BYTES)} with a link you can share in any message.`,
    h1: `Send files up to ${formatFileSize(MAX_UPLOAD_BYTES)}`,
    detailTitle: "More room for the file you need to send",
    detail: "Share a presentation, a collection of files in a ZIP archive, or a video clip without attaching it to an email. Your recipient downloads it from the link.",
    tipTitle: "Before sending a larger file",
    tip: "Keep this page open until your upload finishes. If your file is over 250 MB, compress it or split it into smaller files before uploading.",
    keywords: [
      "large file transfer",
      "send large files",
      "250 mb file share",
      "upload large files",
      "transfer big files",
      "share large files online",
      "free large file transfer",
      "send big files for free",
      "large file sharing website",
      "upload files up to 250 mb",
      "share large apk files",
      ...FILE_SHARING_KEYWORDS,
    ],
  },
  {
    path: "/share-pdf",
    title: "Share PDF files",
    shortTitle: "PDF",
    description:
      "Send a report, resume, or reading material as a PDF with a temporary download link.",
    h1: "Share PDF files",
    detailTitle: "Your document, ready to pass along",
    detail: "Share a finished PDF for someone to read or keep. Recipients download the file and open it in their usual PDF reader.",
    tipTitle: "Send the version you want them to keep",
    tip: "Check your PDF before uploading and give it a recognizable filename. A shared link delivers that version; upload again to share a revised document.",
    keywords: [
      "share pdf",
      "send pdf",
      "pdf file sharing",
      "share pdf online",
      "upload pdf file",
      "share pdf documents",
      "pdf share link",
      "send pdf for free",
      "share pdf with link",
      "share pdf files online",
      ...FILE_SHARING_KEYWORDS,
    ],
  },
  {
    path: "/share-video",
    title: "Share video files",
    shortTitle: "Video",
    description:
      "Send a video clip, screen recording, or edit for review. Share MP4, MOV, and other video files up to 250 MB.",
    h1: "Share video files",
    detailTitle: "Send the clip, keep the conversation moving",
    detail: "Pass a recording to a teammate or send an edit for feedback. Recipients download the uploaded file to watch on their own device.",
    tipTitle: "Choose a file your recipient can play",
    tip: "SwiftShare does not convert or stream videos. Check the file format and size before uploading; trim or compress larger videos to stay within 250 MB.",
    keywords: [
      "share video files",
      "send video online",
      "share videos with link",
      "upload video files",
      "share mp4 online",
      "send video file free",
      "share video clips",
      "video file transfer",
      "share movies and clips",
      "video share link",
      ...FILE_SHARING_KEYWORDS,
    ],
  },
  {
    path: "/share-audio",
    title: "Share audio & music files",
    shortTitle: "Audio",
    description:
      "Pass along a voice recording, podcast draft, or music track with a temporary download link.",
    h1: "Share audio and music files",
    detailTitle: "Let someone hear what you are working on",
    detail: "Send an MP3, WAV, or another audio file for listening or review. Recipients download it to play in their preferred audio app.",
    tipTitle: "Keep the version clear",
    tip: "Add a title or version number to the filename so listeners know which recording they received. Share recordings and music you have permission to distribute.",
    keywords: [
      "share audio files",
      "send audio online",
      "share music files",
      "upload mp3",
      "share songs with link",
      "audio file transfer",
      "share music tracks",
      "share voice recordings",
      "send audio file free",
      "mp3 share link",
      ...FILE_SHARING_KEYWORDS,
    ],
  },
  {
    path: "/share-images",
    title: "Share images & photos",
    shortTitle: "Images",
    description:
      "Share a photo, screenshot, or design file as a download. Send JPG, PNG, WebP, and other image formats.",
    h1: "Share images and photos",
    detailTitle: "Send the image as a file",
    detail: "Hand over a screenshot for feedback or an image for a project. SwiftShare transfers the uploaded file without resizing it or converting its format.",
    tipTitle: "Sharing a set of photos?",
    tip: "Put the images in a ZIP archive to send them together in one upload. The archive must fit within the 250 MB file limit.",
    keywords: [
      "share images online",
      "send photos",
      "share pictures with link",
      "upload images",
      "share photos online",
      "image file sharing",
      "share jpg and png",
      "send photos for free",
      "photo share link",
      "image transfer",
      ...FILE_SHARING_KEYWORDS,
    ],
  },
  {
    path: "/share-zip",
    title: "Share ZIP & compressed files",
    shortTitle: "ZIP",
    description:
      "Bundle a folder or several files into one archive and send them together with a download link.",
    h1: "Share ZIP and compressed files",
    detailTitle: "One archive for everything that belongs together",
    detail: "Keep project files, documents, or photos together in a ZIP archive. Your recipient downloads the archive and extracts it on their device.",
    tipTitle: "Prepare your archive before uploading",
    tip: "Compress the files on your device and check that the finished archive is no larger than 250 MB. SwiftShare transfers archives without opening or extracting them.",
    keywords: [
      "share zip files",
      "send zip archive",
      "upload compressed files",
      "zip file sharing",
      "share archives online",
      "send zip folder",
      "share zip online",
      "compressed file transfer",
      "zip share link",
      "send zip files free",
      ...FILE_SHARING_KEYWORDS,
    ],
  },
  {
    path: "/share-documents",
    title: "Share document files",
    shortTitle: "Docs",
    description:
      "Send a Word document, Excel workbook, or PowerPoint presentation for someone to download and use.",
    h1: "Share documents and presentations",
    detailTitle: "Hand over the file they need to work with",
    detail: "Send a draft for review, a spreadsheet for a teammate, or slides for a meeting. Recipients get the uploaded document to open in a compatible app.",
    tipTitle: "Keep everyone on the same version",
    tip: "Include a date or version in the filename. Changes made after uploading are not synced to the shared file; upload the updated document to create a new link.",
    keywords: [
      "share documents online",
      "send word documents",
      "share excel files",
      "upload documents",
      "share files with link",
      "document sharing",
      "share ppt files",
      "send docs for free",
      "document transfer",
      "share documents with link",
      ...FILE_SHARING_KEYWORDS,
    ],
  },
] as const;
